export const AUTH_STACK = {
  AUTH: 'AUTH',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  LOGIN: 'LOGIN',
};

export const MAIN_STACK = {
  MAIN: 'MAIN',
  HOME: 'HOME',
  RESERVATIONS: 'RESERVATIONS',
  CONTACT: 'CONTACT',
  DOCUMENTS: 'DOCUMENTS',
  FINANCES: 'FINANCES',
};

export default {
  MAIN_STACK,
  AUTH_STACK,
};
